# TCL File Generated by Component Editor 15.0
# Sun Feb 07 18:20:14 EST 2016
# DO NOT MODIFY


# 
# camera2640 "camera2640" v1.0
#  2016.02.07.18:20:14
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module camera2640
# 
set_module_property DESCRIPTION ""
set_module_property NAME camera2640
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP AP
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME camera2640
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL camera2640
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_edge_detector.v VERILOG PATH HDL/altera_edge_detector.v
add_fileset_file camera2640.vhd VHDL PATH HDL/camera2640.vhd TOP_LEVEL_FILE
add_fileset_file camera_init.vhd VHDL PATH HDL/camera_init.vhd
add_fileset_file capture_frame.vhd VHDL PATH HDL/capture_frame.vhd
add_fileset_file frame_ram.qip OTHER PATH HDL/frame_ram.qip
add_fileset_file frame_ram.vhd VHDL PATH HDL/frame_ram.vhd
add_fileset_file i2cm.vhd VHDL PATH HDL/i2cm.vhd
add_fileset_file ov2640reg_rom.vhd VHDL PATH HDL/ov2640reg_rom.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 50000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 avs_address address Input 16
add_interface_port avalon_slave_0 avs_data_out readdata Output 8
add_interface_port avalon_slave_0 avs_rd_req read Input 1
add_interface_port avalon_slave_0 avs_wait waitrequest Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rstn reset_n Input 1


# 
# connection point capture_io
# 
add_interface capture_io conduit end
set_interface_property capture_io associatedClock clock
set_interface_property capture_io associatedReset reset
set_interface_property capture_io ENABLED true
set_interface_property capture_io EXPORT_OF ""
set_interface_property capture_io PORT_NAME_MAP ""
set_interface_property capture_io CMSIS_SVD_VARIABLES ""
set_interface_property capture_io SVD_ADDRESS_GROUP ""

add_interface_port capture_io capture capture Input 1


# 
# connection point debug_io
# 
add_interface debug_io conduit end
set_interface_property debug_io associatedClock clock
set_interface_property debug_io associatedReset reset
set_interface_property debug_io ENABLED true
set_interface_property debug_io EXPORT_OF ""
set_interface_property debug_io PORT_NAME_MAP ""
set_interface_property debug_io CMSIS_SVD_VARIABLES ""
set_interface_property debug_io SVD_ADDRESS_GROUP ""

add_interface_port debug_io debug debug Output 4


# 
# connection point camera_io
# 
add_interface camera_io conduit end
set_interface_property camera_io associatedClock clock
set_interface_property camera_io associatedReset reset
set_interface_property camera_io ENABLED true
set_interface_property camera_io EXPORT_OF ""
set_interface_property camera_io PORT_NAME_MAP ""
set_interface_property camera_io CMSIS_SVD_VARIABLES ""
set_interface_property camera_io SVD_ADDRESS_GROUP ""

add_interface_port camera_io sda sda Bidir 1
add_interface_port camera_io scl scl Bidir 1
add_interface_port camera_io vsync vsync Input 1
add_interface_port camera_io hsync hsync Input 1
add_interface_port camera_io pclk pclk Input 1
add_interface_port camera_io data_in data_in Input 8

