# TCL File Generated by Component Editor 15.0
# Sun Feb 07 10:39:29 EST 2016
# DO NOT MODIFY


# 
# camera2640_i2c "camera2640_i2c" v1.0
#  2016.02.07.10:39:29
# 
# 

# 
# request TCL package from ACDS 15.0
# 
package require -exact qsys 15.0


# 
# module camera2640_i2c
# 
set_module_property DESCRIPTION ""
set_module_property NAME camera2640_i2c
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP AP
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME camera2640_i2c
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ov2640_init
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file camera_init.vhd VHDL PATH HDL/camera_init.vhd TOP_LEVEL_FILE
add_fileset_file i2cm.vhd VHDL PATH HDL/i2cm.vhd
add_fileset_file ov2640reg_rom.vhd VHDL PATH HDL/ov2640reg_rom.vhd
add_fileset_file altera_edge_detector.v VERILOG PATH HDL/altera_edge_detector.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 50000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point i2c_conduit
# 
add_interface i2c_conduit conduit end
set_interface_property i2c_conduit associatedClock clock
set_interface_property i2c_conduit associatedReset reset
set_interface_property i2c_conduit ENABLED true
set_interface_property i2c_conduit EXPORT_OF ""
set_interface_property i2c_conduit PORT_NAME_MAP ""
set_interface_property i2c_conduit CMSIS_SVD_VARIABLES ""
set_interface_property i2c_conduit SVD_ADDRESS_GROUP ""

add_interface_port i2c_conduit sda sda Bidir 1
add_interface_port i2c_conduit scl scl Bidir 1


# 
# connection point io_conduit
# 
add_interface io_conduit conduit end
set_interface_property io_conduit associatedClock clock
set_interface_property io_conduit associatedReset reset
set_interface_property io_conduit ENABLED true
set_interface_property io_conduit EXPORT_OF ""
set_interface_property io_conduit PORT_NAME_MAP ""
set_interface_property io_conduit CMSIS_SVD_VARIABLES ""
set_interface_property io_conduit SVD_ADDRESS_GROUP ""

add_interface_port io_conduit en en Input 1
add_interface_port io_conduit status status Output 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rstn reset_n Input 1

